# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main , develop]

  # Allows you to run this workflow manually from the Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew build
